// The flags every `claude -p` call shares (ref §4); callers add --mcp-config, --safe-mode, ...
export const baseArgs = (o: { model: string; effort: string; systemFile: string; tools: string }) => [
  "-p",
  "--model",
  o.model,
  "--effort",
  o.effort,
  "--input-format",
  "stream-json",
  "--output-format",
  "stream-json",
  "--verbose",
  "--include-partial-messages",
  "--no-session-persistence",
  "--setting-sources",
  "",
  "--strict-mcp-config",
  "--system-prompt-file",
  o.systemFile,
  "--tools",
  o.tools,
];
